/**
 * outreach-helpers.mjs
 *
 * Pure helper functions extracted from generate-cncf-outreach-issues.mjs so
 * they can be unit tested without triggering the CLI's top-level side
 * effects (existsSync/mkdirSync/writeFileSync at import time).
 */

const KB_REPO = 'kubestellar/console-kb'

export function slugify(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

export function titleCase(str) {
  return str.replace(/(?:^|[-_])(\w)/g, (_, c) => ' ' + c.toUpperCase()).trim()
}

export function generateIssueTitle(project) {
  return `🤖 AI-Powered Install Mission for ${titleCase(project.name)} — Community Feedback Welcome`
}

export function generateIssueBody(project, consoleUrl) {
  const CONSOLE_URL = consoleUrl || process.env.CONSOLE_URL || 'https://console.kubestellar.io'
  const slug = slugify(project.name)
  const displayName = titleCase(project.name)
  const missionUrl = `${CONSOLE_URL}/missions/install-${slug}`
  const improveUrl = `https://github.com/${KB_REPO}/issues/new?title=${encodeURIComponent(`Improve AI Mission: ${displayName}`)}&labels=ai-mission,community-improvement&body=${encodeURIComponent(`**Project:** ${displayName}\n**Section:** (install/uninstall/upgrade/troubleshooting)\n\n## What needs improvement?\n\n_Please describe what should be changed._`)}`

  return `## 🚀 AI-Generated Install Mission for ${displayName}

The [KubeStellar Console](${CONSOLE_URL}) now includes an **AI-generated installation mission** for **${displayName}**. This mission provides:

- ✅ **Step-by-step install guide** with copy-pasteable commands
- 🗑️ **Uninstall steps** for clean removal
- ⬆️ **Upgrade/update guide** with backup and rollback
- 🔧 **Troubleshooting** for common issues
- 📊 **Quality scored** by automated gates (schema, security, actionable commands, verification)

### 🔗 View the Mission

**[Open ${displayName} Install Mission →](${missionUrl})**

The mission was generated by synthesizing:
1. Your project's README and documentation
2. Helm charts and values.yaml
3. Kubernetes manifests and examples
4. Latest release information
5. Container image metadata
6. Common configuration patterns

### 🛠️ Help Us Improve It

As the maintainers of ${displayName}, you know your project best. If anything in the mission is:

- ❌ **Wrong** — a command is incorrect or outdated
- ➕ **Missing** — an important step is not covered
- 💡 **Improvable** — there's a better way to do it
- 🔒 **Security concern** — something should be done differently

**[📝 Suggest an Improvement →](${improveUrl})**

Or click the **"Improve this AI Mission"** button directly in the console when viewing the mission.

### 🤖 How It Works

The mission is auto-generated using:
- **6 knowledge sources** crawled from your GitHub repository
- **LLM synthesis** (GitHub Models) to produce structured install guides
- **7-gate quality checks** (schema, security, actionable commands, verification, version pinning)
- **Kind cluster integration testing** — commands are actually executed on a test cluster

Missions are regenerated weekly to stay current with new releases.

### 📦 About KubeStellar Console

[KubeStellar Console](${CONSOLE_URL}) is an open-source Kubernetes management console that provides:
- AI-powered missions for installing and managing CNCF projects
- Cluster monitoring, workload management, and security posture
- Community-driven mission marketplace

**Repository:** [github.com/${KB_REPO}](https://github.com/${KB_REPO})

---

_This issue was auto-generated as part of CNCF-wide outreach. The ${displayName} install mission is maintained in [\`fixes/cncf-install/install-${slug}.json\`](https://github.com/${KB_REPO}/blob/master/fixes/cncf-install/install-${slug}.json)._

_Labels: \`ai-mission\`, \`community\`, \`installation\`_
`
}

export function generateIssueLabels() {
  return ['ai-mission', 'community', 'installation']
}
