name: Feedback Wanted

on:
  pull_request:
    types: [closed]

permissions:
  read-all

jobs:
  feedback:
    permissions:
      pull-requests: write
    uses: kubestellar/infra/.github/workflows/reusable-feedback.yml@main
    secrets: inherit
