name: OpenSSF Scorecard

on:
  schedule:
    - cron: '0 6 * * 1'
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  analysis:
    permissions:
      id-token: write
      security-events: write
      contents: read
      actions: read
    uses: kubestellar/infra/.github/workflows/reusable-scorecard.yml@dd836e89cb97c6e433067497ebcb355a01741aad  # main, post-ghcr fix
    secrets: inherit
